DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Addresses;

CREATE TABLE Addresses (
  ID serial PRIMARY KEY,
  CITY text NULL,
  STREET text NULL,
  NUMBER int NULL,
  NEIGHBOURHOOD text NULL
);

CREATE TABLE Users (
  ID SERIAL PRIMARY KEY,
  NAME text NOT NULL,
  BIRTHDATE date NULL,
  CPF int NOT NULL,
  PASSWORD int NOT NULL,
  EMAIL text NOT NULL,
  COURSE text NULL,
  RG int NOT NULL,
  PHONE int NULL,
  ID_ADDRESS int NULL REFERENCES Addresses (id)
);
